---

- name: ensure configuration dirs are present on system
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
  loop:
    - '/etc/nginx'
    - '/etc/nginx/sites-available'
    - '/etc/nginx/sites-enabled'
    - '/etc/nginx/conf'
  become: true
  tags:
    - nginx
    - config


- name: deploy configuration tempates
  block:
    - ansible.builtin.copy:
        src:  'mime.types'
        dest: '/etc/nginx/conf/mime.types'
        
    - ansible.builtin.template:
        src:  'nginx.conf.j2'
        dest: '/etc/nginx/nginx.conf'
  become: true
  tags:
    - nginx
    - config